// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Wesley",
            "email": "wesley.ch3n.0530@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/concat": {
            "post": {
                "description": "return concat selection csvs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Python"
                ],
                "summary": "concat 2 selection csv",
                "operationId": "concat_selection_file",
                "parameters": [
                    {
                        "description": "files need to be concated",
                        "name": "Files",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ConcatFile"
                        }
                    }
                }
            }
        },
        "/api/export": {
            "post": {
                "description": "return processed selection csv",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Python"
                ],
                "summary": "export selection files",
                "operationId": "export_selection_file",
                "parameters": [
                    {
                        "description": "filtered files",
                        "name": "FltrFile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FltrFile"
                        }
                    },
                    {
                        "description": "selected ranges",
                        "name": "Range",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Range"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ExportFile"
                        }
                    }
                }
            }
        },
        "/api/upload": {
            "post": {
                "description": "upload raw csv and return filtered csvs",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Python"
                ],
                "summary": "Create filtered files",
                "operationId": "upload_create_filtered_data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.FltrFile"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ConcatFile": {
            "type": "object",
            "properties": {
                "ConcatFile": {
                    "type": "string"
                }
            }
        },
        "models.ExportFile": {
            "type": "object",
            "properties": {
                "ExportFile": {
                    "type": "string"
                }
            }
        },
        "models.FltrFile": {
            "type": "object",
            "properties": {
                "cyDb": {
                    "type": "string"
                },
                "cyGt": {
                    "type": "string"
                },
                "cyLt": {
                    "type": "string"
                },
                "cyRt": {
                    "type": "string"
                },
                "rslt": {
                    "type": "string"
                }
            }
        },
        "models.Range": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "integer"
                },
                "start": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "running python process api",
            "name": "Python"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:3001",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "analyze API",
	Description: "analyze python backend",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
