name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_DIR: web
    steps:
    - uses: actions/checkout@v2
    - name: clone front
      run: |
        git clone https://github.com/WesleyCh3n/analyse.d3.web ${{ env.WEB_DIR }}
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: install yarn
      run: npm install -g yarn
    - name: install dependancy
      run: |
        cd ${{ env.WEB_DIR }}
        yarn install
    - name: export web
      run: |
        cd ${{ env.WEB_DIR }}
        yarn export
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build
    - name: ls
      run: |
        ls
    - name: docker build
      run: |
        docker build --build-arg WEB_DIR=${{ env.WEB_DIR }} \
                     -f ./docker/Dockerfile \
                     -t test-server \
                     ./
