---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
            comp_type: tar
            comp_args: -cvf
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
            comp_type: tar
            comp_args: -cvf
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
            comp_type: zip
            comp_args: ''
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: get repo name
        run: echo ::set-env name=REPO_NAME::${{ github.event.repository.name }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build
      - name: Compress things up
        run: |
          ${{ matrix.comp_type }} \
            ${{ matrix.comp_args }} \
            ${{ env.REPO_NAME }}-${{ matrix.target }}.${{ matrix.comp_type }} \
            analyze.api${{ matrix.suffix }}
          ls
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}-${{ matrix.target }}
          path: |
            ${{ env.REPO_NAME }}-${{ matrix.target }}.${{ matrix.comp_type }}
  pre-release:
    needs: build
    name: "Pre-release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get repo name
        run: echo ::set-env name=REPO_NAME::${{ github.event.repository.name }}
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.REPO_NAME }}-x86_64-apple-darwin.tar
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.REPO_NAME }}-x86_64-unknown-linux-gnu.tar
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.REPO_NAME }}-x86_64-pc-windows-msvc.zip
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ env.REPO_NAME }}-x86_64-apple-darwin.tar
            ${{ env.REPO_NAME }}-x86_64-unknown-linux-gnu.tar
            ${{ env.REPO_NAME }}-x86_64-pc-windows-msvc.zip
